name: Run Selenium Script

on:
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Selenium and ChromeDriver dependencies
      run: |
        pip install selenium
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -N https://chromedriver.storage.googleapis.com/128.0.6613.119/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium Script
      run: python script.py
